services:
  app:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - "/app/node_modules" # making sure not to attach to host node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["npm", "run", "start"]
